@startuml

actor Role as "Role"

rectangle Database

rectangle "HR System" {
    usecase UC1 as "Get world countries
    sorted by population"

    usecase UC1a as "Print report"

    Role - UC1
    UC1 ..> UC1a : include
    UC1 - Database
}

@enduml